### ISSUE TITLE
Streamlit Support

### ISSUE THREAD

**Issue by AndreasInk** [pdkit/pdkit#131]
## Expected Behavior
Not applicable, however, it would be beneficial to have a data web app using a framework called Streamlit for easier testing.  A feature could be dragging and dropping tremor data into the web app and the data would process and return the results in a table and graph format. Happy to implement this as I have a lot of practice with Streamlit, please let me know if this is something I can/should do.

## Actual Behavior
Not applicable

## Steps to Reproduce the Problem
Not applicable

## Specifications
Not applicable

**Comment by gkroussos** [comment]
Thank you for your interest, however a web app does not fit with the pattern of use of this software so we politely decline your very kind offer.
